# Generated by Django 3.1.5 on 2021-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
            ],
        ),
    ]
