# Generated by Django 3.1.5 on 2021-01-21 14:27

from django.db import migrations, models
import jop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('jop_app', '0003_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='image',
            field=models.ImageField(default='', upload_to=jop_app.models.image_upload),
            preserve_default=False,
        ),
    ]
