# Generated by Django 3.1.5 on 2021-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop_app', '0004_jop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
