# Generated by Django 3.1.5 on 2021-01-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop_app', '0005_jop_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jop_Applier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_letter', models.TextField(max_length=500)),
            ],
        ),
    ]
