# Generated by Django 3.1.5 on 2021-01-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop_app', '0006_jop_applier'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop_applier',
            name='jop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Apply_Jop', to='jop_app.jop'),
            preserve_default=False,
        ),
    ]
